export type AccountStackParamList = {
  AccountHome: undefined;
  Profile: undefined;
  AvatarEdit: undefined;
  SecurityCenter: undefined;
  ChangePassword: undefined;
  TwoFA: undefined;
  Passkeys: undefined;
  FundPassword: undefined;
  AntiPhishing: undefined;
  Sessions: undefined;
  LoginHistory: undefined;
  WithdrawalLimits: undefined;
  Whitelist: undefined;
  AppLockSettings: undefined;
  KYCHub: undefined;
  KYCDocument: undefined;
  KYCResult: undefined;
  Preferences: undefined;
  FeeTier: undefined;
  ReferralHome: undefined;
  ReferralList: undefined;
  ReferralShare: undefined;
  ApiKeys: undefined;
  CreateApiKey: undefined;
  ApiKeyDetail: { id: string };
  HelpFaq: undefined;
  SupportTickets: undefined;
  CreateTicket: undefined;
  TicketDetail: { id: string };
  Notifications: undefined;
  NotificationDetail: { id: string };
  Announcements: undefined;
  AnnouncementDetail: { id: string };
  DataExport: undefined;
  About: undefined;
  SystemStatus: undefined;
  LegalViewer: { doc: string };
  AccountDeletion: undefined;
};
