/** Maps backend error codes to UX handling — Sprint 1+ screens consume. */
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMITED: 'RATE_LIMITED',
  KYC_REQUIRED: 'KYC_REQUIRED',
  SANCTIONS_BLOCKED: 'SANCTIONS_BLOCKED',
  TRADING_HALT: 'TRADING_HALT',
  WITHDRAWAL_DISABLED: 'WITHDRAWAL_DISABLED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Pass-through map — backend codes preserved for Sprint 1 UX routing. */
export const ERROR_CODE_MAP: Record<string, ErrorCode> = {
  UNAUTHORIZED: ERROR_CODES.UNAUTHORIZED,
  RATE_LIMITED: ERROR_CODES.RATE_LIMITED,
  KYC_REQUIRED: ERROR_CODES.KYC_REQUIRED,
  SANCTIONS_BLOCKED: ERROR_CODES.SANCTIONS_BLOCKED,
  TRADING_HALT: ERROR_CODES.TRADING_HALT,
  WITHDRAWAL_DISABLED: ERROR_CODES.WITHDRAWAL_DISABLED,
};
