export const CACHE_KEYS = {
  markets: 'cache.markets',
  favorites: 'markets.favorites',
  recentMarkets: 'markets.recent',
  preferences: 'prefs.user',
  onboarding: 'prefs.onboarding',
  language: 'prefs.language',
  theme: 'prefs.theme',
  appLockEnabled: 'prefs.appLock.enabled',
  appLockTimeout: 'prefs.appLock.timeout',
  marketSort: 'markets.sort',
  marketSortDir: 'markets.sortDir',
  marketCategory: 'markets.category',
  quoteCurrency: 'markets.quote',
  guestMode: 'prefs.guestMode',
  walletHistoryFilters: 'wallet.history.filters',
  p2pOrderRoomDraft: (orderId: string) => `p2p.orderRoom.${orderId}.draft`,
  p2pOrderRoomIdempotency: (orderId: string, action: string) =>
    `p2p.orderRoom.${orderId}.idem.${action}`,
} as const;
